# Generated by Django 3.0.5 on 2020-04-28 16:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200428_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CS', 'CS'), ('Mech', 'Mech'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('CHEM', 'CHEM'), ('ETX', 'ETX'), ('Civil', 'Civil'), ('FY', 'FY')], default='CS', max_length=100)),
                ('academic_year', models.CharField(choices=[('FY', 'I'), ('SY', 'II'), ('TY', 'III'), ('BE', 'IV')], default='I', max_length=100)),
                ('batch', models.CharField(blank='True', max_length=3, validators=[django.core.validators.RegexValidator(message='example A14', regex='^[ABCD][1-5][1-5]$')])),
                ('roll_no', models.CharField(blank='True', max_length=2, validators=[django.core.validators.RegexValidator(message='example A14', regex='^[1-85]$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
