# Generated by Django 3.0.5 on 2020-04-28 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200428_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_student',
            name='roll_no',
            field=models.CharField(blank='True', max_length=3, validators=[django.core.validators.RegexValidator(message='example 70', regex='^\\d{2}$')]),
        ),
    ]
