# Generated by Django 3.0.5 on 2020-04-28 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_auto_20200428_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('CS', 'CS'), ('Mech', 'Mech'), ('ENTC', 'ENTC'), ('IT', 'IT'), ('CHEM', 'CHEM'), ('ETX', 'ETX'), ('Civil', 'Civil'), ('FY', 'FY')], default='CS', max_length=100)),
                ('post_of_teacher', models.CharField(blank='True', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
