# Generated by Django 2.1.1 on 2020-06-26 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile_teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='bldg',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I')], default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='flat_no',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.RegexValidator(message='Floor 1 to 14', regex='^[1-14]0[1-4]$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='society',
            field=models.CharField(choices=[('Smondo3', 'Smondo 3.0'), ('Other', 'Other')], default='Smondo 3.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank='True', help_text='10 digit. start with 9,8,7 or 6', max_length=10, validators=[django.core.validators.RegexValidator(message='Required 10 digits. Starting with 9,8,7, or 6', regex='^[9876]\\d{9}$')]),
        ),
        migrations.DeleteModel(
            name='Profile_Student',
        ),
        migrations.DeleteModel(
            name='Profile_Teacher',
        ),
    ]
