# Generated by Django 2.1.1 on 2020-06-26 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200626_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='flat_no',
            field=models.CharField(blank=True, default=1, help_text='0001 to 1404', max_length=10, validators=[django.core.validators.RegexValidator(message='Floor 1 to 14', regex='^[1-14]0[1-4]$')]),
        ),
    ]
