# Generated by Django 2.1.1 on 2020-06-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200626_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='floor',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14)], default=1, help_text='1 to 14', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='flat_no',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=10),
        ),
    ]
