/*
 (c) Skimlinks 2009-2020
 Build time: Tue, 07 Apr 2020 10:21:57 GMT
 Version: "14.0.1-stackpath"
*/
(function(){function Ab(a){u(cd,function(b){null!==b.iabVendorId&&Bb(b.iabVendorId,a)});u(x.partner_consents,function(b,c){var d=va();var e=F(x,["partner_consents",String(c)]);d=46!==c&&e?e.consent:d;d!==a&&Bb(c,a)});wa(x,["skimlinks_consent"],a)}function Bb(a,b){wa(x,["partner_consents",String(a),"consent"],b)}function va(){return F(x,["skimlinks_consent"],null)}function dd(a){function b(a,b){if(!(!a.parentNode||xa(a,e)||a.meta&&a.meta.ReadOnly)){var c=ed(a,b)[0];u(c,function(a){!g[a]&&fd(a)&&(g[a]=
!0,m.domain_data.domains.push(a))})}}var c=z.get_as_hash_node_dict(),d=Object.keys(c).length;if(d){var e=gd(hd.concat(Db())),g={},n=U(function(a){V(a)}),h=0;u(c,function(c,e){window.setTimeout(function(){try{b(c,e)}catch(Cb){n(Cb)}finally{h+=1,h===d&&a(Object.keys(g))}},0)})}else a([])}function id(a){var b;var c=b=null;var d=5;a.Limit&&(d=a.Limit);var e=function(){return a.Priority||0};return{group_id:function(){return b?b.id():0},dec_limit:function(){return d-1},limit:function(){return d},action_type:function(){return a.ActionType},
text:function(){return a.OriginalPhrase},start_byte:function(){return a.StartByte},url:function(){return a.Url},multi:function(){return a.Mt?!0:!1},group_priority:function(){return b?b.group_priority():e()},id:function(){return c?c:a.PhraseId},groups:function(){var b;return(b=a.Groups)?b:[]},title:function(){return a.Unlinked?"":null!=a.ActionTitle?a.ActionTitle:"Shopping link provided by SkimWords"},set_title:function(b){a.Title=a.Unlinked?"":b},occurrence:function(){return a.PhraseOccurrence},set_group:function(a){return b=
a},set_id:function(a){return c=a}}}function jd(){var a=v.linksImpressions;a={phr:a.skimwords.urls,unl:a.unlinked.urls,slc:a.skimlinks.count,swc:a.skimwords.count,ulc:a.unlinked.count,jsl:(new Date).getTime()-v.loading_started,pref:k.referrer,uc:ya,t:1,jsf:"",jv:ea};fa&&(a.xrf=1);return Eb(a)}function Fb(a,b){var c=a.style.cssText;""!==c&&(c+=" ");var d=f("link_background");d&&(-1===d.indexOf("#")&&(d="#"+d),c+="background-color: "+d+" !important; ");null!==f("link_tooltip",null)&&(a.title=f("link_tooltip"));
b&&(Oa&&(d=Oa,-1===d.indexOf("#")&&(d="#"+d),c+="color: "+d+" !important; "),Pa&&(c+="font-weight: "+Pa+" !important; "),ha&&(c="double"===ha?c+"border-bottom: 1px double !important; ":"dashed"===ha?c+"border-bottom: 1px dashed !important; ":c+("text-decoration: "+ha+" !important; ")),Qa&&(c+="font-style: "+Qa+" !important; "),f("skimwords_link_style")&&(d=f("skimwords_link_style"),c+=d+"; "),f("skimwords_link_class")&&(a.className=A(a.className+" "+f("skimwords_link_class"))),Ra&&(a.title=Ra),null===
a.getAttribute("title")&&(a.title="Shopping link added by SkimWords"),a.getAttribute("data-skim-creative")&&(d=parseInt(a.getAttribute("data-skim-creative"),10)%10,1===d||2===d))&&(a.title="");a.style.cssText=c;return!0}function Sa(a,b){b=b||Gb(a);if(!b)return!0;Hb(b);var c=f("skimlinks_keywee_pixel",null);var d=q(l.location.href,"utm_campaign=fbkw");c&&d&&Ib(c);f("vglnk")&&W(b,"skimwords-link")&&(a&&a.stopPropagation?a.stopPropagation():(c=l.event,c.cancelBubble=!0));return!0}function Hb(a,b){a&&
a.nodeName&&"A"!==a.nodeName.toUpperCase()&&"AREA"!==a.nodeName.toUpperCase()&&(a=Jb(a));if(a){var c=kd(a);var d=m.waypointDomain;if(c.length>=d.length&&c.substr(0,d.length)===d)return!0;if(-1!==c.indexOf(d))d=c;else{d=a;var e=W(d,"skimwords-link"),g=D(d,"data-skim-creative"),n=D(d,"data-skimlinks-tracking")||ya,h=Ta?"&"+Ta:"";c=y(Ua(),{id:Kb,isjs:1,jv:ea,sref:l.location,url:c,xguid:k.cookie,xs:1,xtz:Lb(),xuuid:k.uuid});g&&(c.xcreo=g);k.isAdblockUser&&(c.abp=1);X&&(c.site=X);n&&(c.xcust=n);e&&(c.xs=
2,c.xword=D(d,"data-skimwords-word")||"");e=O(d);e.icust&&(c.xjsf=e.icust);e.sourceApp&&(c.xs=e.sourceApp);e.clientClickId&&(c.cci=e.clientClickId,delete O(d).clientClickId);d=m.waypointDomain+"/?"+ia(c)+h}Mb(a,d,b)}return!0}function Jb(a){for(;a.parentNode;){a=a.parentNode;var b=a.nodeName.toUpperCase();if("A"===b||"AREA"===b)return a}return null}function Nb(a,b,c){a=l.skimlinks_settings&&l.skimlinks_settings[a]||l[a];return K(a)?b:p(c)?c(a,b):a}function f(a,b,c){if(P(a)){a:{void 0===a&&(a=[]);for(var d=
0;d<a.length;d++){var e=Nb(a[d]);if(!K(e)){if(p(c)){b=c(e,b);break a}b=e;break a}}}return b}return Nb(a,b,c)}function Ob(){return F(za(),["runTimeInfo","isAdblockUser"])}function ld(a){var b=document.createElement("a"),c={};b.href=a;if(a=b.search.substring(1))for(a=a.replace(/&amp;/g,"&").split("&"),b=0;b<a.length;b++){var d=a[b].split("=");c[d[0]]=d[1]||null}return c}function Q(a){return a.replace(/^www\./i,"")}function Va(){for(var a="",b=0;8>b;b++)a+=Math.floor(65536*(1+Math.random())).toString(16).substring(1);
return a}function p(a){return"[object Function]"===Object.prototype.toString.call(a)}function H(a,b,c){for(var d=0,e=null===a?0:a.length;d<e;)c=b(c,a[d],d,a),d+=1;return c}function Aa(a){return"console"in window&&p(window.console[a])?window.console[a]:function(){}}function Ba(a,b){return H(b,function(b,d){return b&&p(a[d])},!0)}function md(){try{var a=JSON.stringify({a:1});return 1===JSON.parse(a).a}catch(b){return!1}}function B(a,b){var c=Error(b);c.name=a;Pb(c,"getPrototypeOf"in Object?Object.getPrototypeOf(this):
this.__proto__);Error.captureStackTrace&&Error.captureStackTrace(c,B);return c}function Pb(a,b){"setPrototypeOf"in Object?Object.setPrototypeOf(a,b):a.__proto__=b}function K(a){return"undefined"===typeof a||null===a}function P(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)}function G(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function u(a,b){if(P(a))for(var c=0;c<a.length;c++)b(a[c],c,a);else for(c in a)G(a,c)&&b(a[c],c,a)}function y(){var a=
arguments[0],b=Array.prototype.slice.call(arguments,1);K(a)&&(a={});u(b,function(b){K(b)&&(b={});u(Object.keys(b),function(c){a[c]=b[c]})});return a}function Wa(a,b){var c=[];u(a,function(d,e){b(d,e,a)&&c.push(d)});return c}function Qb(a){void 0===a&&(a=[]);return Wa(a,function(a){return!!a})}function Xa(a,b){if(!a)return[];if(!b)return[].concat(a);var c=[];u(a,function(d,e){c.push(b(d,e,a))});return c}function A(a){return K(a)?"":a.toString().replace(/^[\s\xA0]+|[\s\xA0]+$/g,"")}function I(a){return"boolean"===
typeof a}function R(a,b){return"undefined"===typeof a?b:a}function Ya(a,b,c){a=R(a,"");b=R(b,"");c=R(c,0);return 0===a.slice(c).indexOf(b)}function Ca(a,b,c){a=R(a,"");b=R(b,"");c=R(c,0);c=c<a.length?c|0:a.length;return a.substr(c-b.length,b.length)===b}function Za(a){return encodeURIComponent(a).replace(/[!'()*~]/g,function(a){return"%"+a.charCodeAt(0).toString(16).toUpperCase()})}function ja(a,b){void 0===b&&(b=!0);var c=document.createElement("a");if(b)var d=a;else{d=void 0;void 0===d&&(d="http");
var e="";/^https?:\/\//.test(a)||/^\/[^/]+/.test(a)||(e=/^\/\//.test(a)?d+":":d+"://");d=""+e+a}c.href=d;try{return Q(c.hostname)}catch(g){return""}}function Rb(a){a=a.replace(/^\??/,"").split("&");return H(a,function(a,c){if(!c)return a;var b=c.split(/=/),e=b[0];if(1===b.length)return a[e]=!0,a;a[e]=decodeURIComponent(b.splice(1).join(""));return a},{})}function Sb(a){var b=Rb(window.location.search);return G(b,a)}function ia(a,b){var c=[];b=b||Za;u(a,function(a,e){c.push(e+"="+b(a))});return c.join("&")}
function $a(a,b,c,d){function e(){if(p(d.onError)){var b=400<=r.status&&500>r.status,c=500<=r.status&&600>r.status;d.onError(new (0===r.status?nd:b?od:c?pd:qd)(h+" "+a+" "+r.status))}}b=b||{};d=d||{};var g=d.data,n=d.headers||{},h=d.method||"GET",r=new XMLHttpRequest;d.withCredentials&&(r.withCredentials=!0);b=ia(b);b.length&&(a=a+"?"+b);r.open(h,a);u(n,function(a,b){r.setRequestHeader(b,a)});r.onload=function(){if(p(c))if(200<=r.status&&300>r.status){try{var a=JSON.parse(r.responseText)}catch(Cb){a=
r.responseText}c(a)}else e()};r.onerror=e;r.send(g);return r}function F(a,b,c){if(!a||!b||!b.length)return c;for(var d=b.length,e=0;e<d;e++){var g=b[e];if(a&&g in a)a=a[g];else return c}return a}function za(){return window.__SKIM_JS_GLOBAL__&&p(window.__SKIM_JS_GLOBAL__.getDebugInfo)?window.__SKIM_JS_GLOBAL__.getDebugInfo():{}}function rd(a){var b=/(?::(\d+))?:(\d+)$/,c=/^([^ ]+)\s\((.*)\)$/,d={filename:a,"function":"?",lineno:null,colno:null,in_app:!0};c.test(a)&&(a=a.match(c).slice(1),c=a[1],d["function"]=
a[0],d.filename=c);b.test(d.filename)&&(c=d.filename.match(b).slice(1),a=c[0],c=c[1],a&&c?(d.lineno=parseInt(a,10),d.colno=parseInt(c,10)):!a&&c&&(d.lineno=parseInt(c,10)),d.filename=d.filename.replace(b,""));return d}function sd(a){a=a.stack.replace(a.toString(),"").replace(/^\s+at\s+/gm,"").split("\n");a=Xa(a,function(a){return A(a)});a=Qb(a);a.reverse();return Xa(a,rd)}function V(a,b){if(a&&Tb){Ub.push(a);try{td.sendError(a,b)}catch(d){if(d===a)Vb.error(a);else{var c=new ud;c.__sentryExtraData__=
{logger_error_message:d.message,logger_error_stack:d.stack,initial_error_message:a.message,intial_error_stack:a.stack};throw c;}}}}function E(a){return p(a)?function(){try{a.apply(this,arguments)}catch(b){V(b)}}:a}function U(a){var b=!1,c;return function(){if(b)return c;c=a.apply(this,arguments);b=!0;return c}}function Wb(a,b){return P(a)?a:b}function D(a,b,c){3<=arguments.length&&("undefined"!==typeof a.setAttribute?a.setAttribute(b,c):a[b]=c);try{var d=a[b];d||(d=a.getAttribute(b));return d}catch(e){return null}}
function J(a,b){var c=Array.prototype.slice.call(arguments,2),d=E(a);return window.setTimeout.apply(window,[d,b].concat(c))}function vd(a,b){function c(){a.href=a.skimlinksOriginalHref;delete a.skimlinksOriginalHostname;delete a.skimlinksOriginalHref;delete a.skimlinksRestoreSwappedLink}b=b||Xb;var d=J(c,b);a.skimlinksOriginalHostname=a.hostname;a.skimlinksOriginalHref=a.href;a.skimlinksRestoreSwappedLink=function(){clearTimeout(d);c()}}function Mb(a,b,c){if(a){"string"===typeof a.skimlinksOriginalHref||
vd(a,c);c=null;var d=a.childNodes.length&&3===a.childNodes[0].nodeType;"msie"===k.detect.browser&&d&&(c=a.innerHTML);a.href=b;c&&c!==a.innerHTML&&(a.innerHTML=c)}}function ab(a,b){var c=b?b.charAt(0).toUpperCase()+b.slice(1):"";return a["skimlinksOriginal"+c]||a[b]}function Yb(a){var b=a.href;b=k.cookie?b.replace(/([&?])xguid=([a-fA-F0-9]{32})/,"$1xguid="+k.cookie):b.replace(/([&?]xguid=[a-fA-F0-9]{32})/,"");b!==a.href&&Mb(a,b);return b}function Zb(a){a=a||document;a=a.body||a.getElementsByTagName("body")[0];
if(!a)throw new $b;return a}function Ib(a,b,c){if(!L){L=document.createElement("iframe");L.id="skimlinks-pixels-iframe";try{Zb().appendChild(L)}catch(g){g instanceof $b&&document.documentElement.appendChild(L)}var d=L;d.width=0;d.height=0;d.style.display="none"}var e=L.contentDocument||L.contentWindow.document;d=Zb(e);d||(d=document.createElement("body"),e.appendChild(d));e=e.createElement("img");e.src=a;e.width=1;e.height=1;p(b)&&(e.onload=E(b));p(c)&&(e.onerror=E(c));d.appendChild(e)}function Ua(){var a=
{};bb&&(a.dnt=bb);ac&&(a.fdnt=1);return a}function ka(a,b,c,d){var e=d||{};d=e.usePixel||!1;var g=e.useSendBeacon||!1;e=e.callback||function(){};c=y({},c,Ua());g?bc(a,b,c,e):d?cc(a,b,c,e):cb(a,b,c,e)}function bc(a,b,c,d){b=JSON.stringify(b);return navigator.sendBeacon&&(a=db(a,c),navigator.sendBeacon(a,b))?(d&&d(),!0):!1}function cc(a,b,c,d){c=y({},c);c.rnd=Math.random();b&&(c.data=JSON.stringify(b));Ib(db(a,c),d,d)}function cb(a,b,c,d){b=JSON.stringify(b);Da.post(db(a,c),{},d,{headers:{"Content-type":"text/plain"},
data:b,withCredentials:!0})}function db(a,b){var c=ia(b),d=""+wd+a;return c?d+"?"+c:d}function q(a,b){return p(a.indexOf)?-1<a.indexOf(b):!1}function Ea(a){return q(a,dc)||q(a,"go.redirectingat.com")||q(m.waypointDomain,a)}function xd(a,b){if(!a)throw Error("[matchSelector] First argument needs to be an html element.");var c=window.Element.prototype;c=c.matches||c.msMatchesSelector||c.mozMatchesSelector||c.webkitMatchesSelector;if(p(c))try{return c.call(a,b)}catch(e){return!1}c=(a.document||a.ownerDocument).querySelectorAll(b);
for(var d=0;c[d]&&c[d]!==a;)d+=1;return!!c[d]}function xa(a,b){var c=yd(a);if(!c||!P(b)||0===b.length)return!1;var d=b.map(function(a){return a+" *"}).concat(b).join(",");return xd(c,d)}function yd(a){for(;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.parentNode;return a}function eb(a,b){for(var c=0;c<a.length;c++)if(b(a[c]))return a[c]}function Y(a,b){if("function"!=typeof a||null!=b&&"function"!=typeof b)throw new TypeError("Expected a function");if(!Y.Cache)return a;var c=function e(){for(var c=arguments.length,
n=Array(c),h=0;h<c;h++)n[h]=arguments[h];c=b?b.apply(this,n):n[0];h=e.cache;if(h.has(c))return h.get(c);n=a.apply(this,n);e.cache=h.set(c,n)||h;return n};c.cache=new Y.Cache;return c}function ec(a,b){return!!eb(b,function(b){var c=Ya("*"),e=Ca("*"),g=b.replace(/\*/g,"");return c&&e?q(a,g):c?Ca(a,g):e?Ya(a,g):a===b})}function fb(a,b){return a&&a.length&&b?"undefined"!==typeof eb(a,b):!1}function zd(a){return f("_merchantSettings")?fb(Ad,function(b){return q(a,b)}):!1}function fc(a){if(!a||!a.href)return!0;
var b=A(ab(a,"href"));(b=!gc(b))||(b=[].concat(Bd(),Db(),hc),b=b.length&&xa(a,b)?!0:gb.length?!xa(a,gb):!1);return b}function gc(a){if(!a||zd(a))return!1;var b=m.hostname;var c=R(void 0,!0);c=ja(a,c);var d=Ca(c,"."+b)||Ca(b,"."+c);if(b=c!==b&&!d)a=ja(a),a=Fa.length?!ec(a,Fa):ec(a,Cd()),b=!a;return b}function Dd(a){var b;if(b=ic)null===a.offsetParent?b=!0:(b=l.getComputedStyle,b=p(b)?"hidden"===b(a).visibility:!1);if(b)return w.IGNORE;var c=A(ab(a,"href"));b=Q(ab(a,"hostname"));c=c?/^https?:\/\//.test(c)||
/^\/\//.test(c):!1;if(c&&!fc(a)){if(fa)return w.TRACK;if(!0===m.aff_domains[b]||G(hb,b))return w.AFFILIATE;if(Ea(b))return w.PRE_AFFILIATED;if(a=ib)a=!G(m.aff_domains,b)||K(m.aff_domains[b]);return a?w.UNKNOWN:""===k.cookie&&jc?w.AFFILIATE:w.TRACK}return w.IGNORE}function W(a,b){if(!a||!a.className||!b)return!1;var c=a&&a.className?A(a.className).split(/\s+/):[];return q(c,b)}function wa(a,b,c){if(!a||!b||!b.length)return a;for(var d=b.length,e=a,g=null,n=0;n<d;n++){var h=b[n];if(n===d-1){try{a[h]=
c}catch(r){e[g]={},e[g][h]=c}break}(e=!(h in a))||(e=a[h],g=typeof e,e=!(null!==e&&("object"===g||"function"===g)));e&&(a[h]={});e=a;g=h;a=a[h]}return a}function kc(a){if("string"!==typeof a.skimlinksOriginalHref)return!1;var b=O(a);b=Ed(a.href,b);a.href=b;return!0}function Ed(a,b){var c=ld(a);b.icust&&b.icust!==c.xjsf&&(c.xjsf=Za(b.icust));b.sourceApp&&b.sourceApp!==c.xs&&(c.xs=b.sourceApp);c=ia(c,function(a){return a});return m.waypointDomain+"?"+c}function O(a){if(!a)throw Error("getAnchorMetaData takes an anchor HTML element as an argument");
var b=F(a,[lc]);b||(b={icust:null,sourceApp:null},wa(a,[lc],b));return b}function Gb(a){a=a.target||a.srcElement||a.originalTarget;if(!a)return null;var b=(a.nodeName||"").toLowerCase();return q(["a","area"],b)?a:Jb(a)}function Ga(a){try{return a()}catch(b){}}function Fd(a){var b=f("gtag");Ga(function(){b("event",Z,{event_category:"click",event_label:a})})}function Gd(a){var b=f("ga");Ga(function(){b("send","event","click",Z,a)})}function Hd(a){var b=f("_gaq");Ga(function(){b.push(["_trackEvent",
"click",Z,a])})}function Id(a){var b=f("pageTracker");b._trackPageview&&Ga(function(){b._trackPageview("/"+Z+"/"+a)})}function Jd(a,b){return H(Object.keys(b),function(c,d){var e=a[d]===b[d];return c&&e},!0)}function mc(a){return H(a,function(a,c){return a.concat(c)},[])}function Ha(a){a=a?"."+a:"";return mc(M.querySelectorAll("a[href]"+a+", area[href]"+a))}function t(a,b,c){b in a?Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}):a[b]=c;return a}function Kd(a,b){u(a,
function(a){var c=q(b,a)&&!Ea(a);m.aff_domains[a]=c})}function Ld(a,b){return!fb(a,function(a){return!b(a)})}function Md(){for(var a=new aa,b=arguments.length,c=Array(b),d=0;d<b;d++)c[d]=arguments[d];a.waitFor(c);return a}function jb(a){var b=nc[a];if(!b)throw Error("Unknown service "+a);return b}function Nd(a){var b=D(a,"rel"),c=Q(a.hostname);!b&&c&&!0===m.aff_domains[c]&&D(a,"rel","nofollow")}function Od(){oc&&u(Ha(),Nd)}function Pd(a){if(a.affiliationType===w.IGNORE)return!1;var b=a.anchor,c=a.affiliationType,
d=a.nativeEvent;if(a.type===S.LEFT_CLICK)if(b=a.anchor,c=a.affiliationType,c===w.AFFILIATE||c===w.UNKNOWN){b=a.anchor;c=a.nativeEvent;d=a.clientClickId;var e,g,n;if(n=f("skimlinks_strip_attribute",!1))for(g in n)if(G(n,g)){var h=n[g];(e=D(b,g))&&0===e.indexOf(h)&&(e=e.substr(h.length),D(b,g,e))}la&&D(b,"target",la);O(a.anchor);O(b).clientClickId=d;kc(b);Z&&(a=b.href,f("gtag")?Fd(a):f("ga")?Gd(a):f("_gaq")?Hd(a):f("pageTracker")&&Id(a));a=pc?(a=D(b,"onclick"))&&q(a.toString(),"return false")?!0:(a=
b.onclick)&&p(a)&&q(a.toString(),".preventDefault()")?!0:!1:!1;a?(Sa(c,b),(la?l.open(b.href,la):l.open(b.href,"_blank")).focus()):Sa(c,b)}else c===w.PRE_AFFILIATED?Yb(b):c===w.TRACK&&(a={publisher_id:ma,publisher_domain_id:na,referrer:l.location.toString(),pref:k.referrer,site:""+X,url:b.href,custom:D(b,"data-skimlinks-tracking")||ya||"",xtz:k.timezone,uuid:k.uuid,product:"1"},fa&&(a.xrf=1),ka("/naclicks",a,null,{usePixel:!0}));else{try{if(n=O(b),!n.icust||-1!==n.icust.indexOf("other_click__")){e=
"other_click__"+d.type+" ["+(void 0!=d.button?d.button:"")+"]";if(32<String(e).length)throw Error(e+" is not a valid icust value. The value should be less than 33 chars");O(b).icust=e;kc(b)}}catch(r){}c===w.AFFILIATE||c===w.UNKNOWN?Hb(b,200):c===w.PRE_AFFILIATED&&Yb(b)}return!0}function Qd(){jb(ba.ANCHOR_CLICK_INTERCEPTOR).registerInterceptor(Pd,oa.SKIMLINKS)}function Rd(){k.skimlinksEnabled&&(C.on("skim_js_start",Qd),T.whenBeaconFullyReady(Od))}function qc(a){var b;return a&&-1!==a.indexOf("class=")&&
(b=a.match(/([^[]+)\[class=([^\]]+)\]/i))&&3===b.length?b[1]+"."+b[2]:a}function Sd(){var a=Ha();return H(a,function(a,c){var b=Q(c.hostname),e=b&&!fc(c)&&!Ea(b),g=G(m.aff_domains,b);e&&!g&&(a.push(b),m.aff_domains[b]=null,m.domain_data.domains.push(b));return a},[])}function rc(a){var b=Sd();return T.sendBeaconRequest(b,a)}function sc(a,b){u(a,function(a){void 0===m.aff_domains[a]&&(m.aff_domains[a]=null)});T.sendBeaconRequest(a,ca.AUX).readyState.whenReady(b)}function Eb(a){return y({pag:l.location.href,
guid:k.cookie,uuid:k.uuid,tz:k.timezone,publisher_id:ma,publisher_domain_id:na},a)}function tc(a){if(0!==v.awaitedModules.length&&(v.awaitedModules=Wa(v.awaitedModules,function(b){return b!==a}),0===v.awaitedModules.length)){var b=jd();ka("/page",b)}}function Td(a){a=a.match.phrase;return{w:a.text(),lp:a.url(),t:Ia.creative}}function kb(a){a=a||[];var b=H(a,function(a,b,e){a[e]=b;return a},{});v.linksImpressions.unlinked={count:a.length,urls:b};tc("unlinked")}function lb(a){return String(a).replace(/</g,
"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function gd(a){return H(a,function(a,c){return q(a,c)?a:a.concat(c)},[])}function mb(a,b,c,d){void 0===d&&(d=!1);if(a&&(a.nodeName||a===l))if(M.addEventListener){var e=E(c.bind(a));a.addEventListener(b,e,d)}else a.attachEvent("on"+b,function(){return 7>k.detect.version&&!l.event?(J(c.bind(a,l.event),100),!0):c.call(a,l.event)})}function uc(a,b){Sa(a,b)}function Ud(){l.__SKIM_JS_GLOBAL__.bundledEntries.unlinked=!0;if(k.unlinkedEnabled){if(k.skimwordsEnabled)C.on("instant_api_callback_settings",
Vd);else T.whenPostPageLoadBeaconCallCompleted(vc);C.on("dom_changed",wc)}}function Vd(){var a=pa.settings;2===a.nc?k.unlinkedEnabled&&sc(m.domain_data.domains,xc):k.unlinkedEnabled&&(a.includes?(N&&N.length&&(a.excludes=a.excludes.concat(N)),z.traverse(a.includes,a.excludes,a.read_onlys)):N&&N.length?z.traverse(["body"],N,[]):z.traverse(["body"],[],[]));vc()}function vc(){a:{var a=M.getElementsByTagName("body");if(a.length){a=a[0].textContent||a[0].innerText;var b;if(b=a)a=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^[\]\s]*\b|$/gi.exec(a),
b=a.length&&""!==a[0]?!0:!1;if(b){a=!0;break a}}a=!1}a?(k.skimwordsEnabled||z.traverse([],N,[]),wc()):kb()}function wc(){dd(function(a){a.length?sc(a,xc):kb()})}function xc(){var a=[];Object.keys(m.aff_domains).length&&(u(Ia.url_spans,function(b){m.aff_domains[b.match.domain]&&(Wd(b.node,b.match,!0),a.push(Td(b)))}),J(function(){var a;var c=Ha("skimlinks-unlinked");var d=[];var e=0;for(a=c.length;e<a;e++){var g=c[e];d.push(Xd(g))}return d},10));kb(a)}function Yd(a){var b=Math.random(),c=0;return eb(a,
function(a){a=c+a.weight;if(b<a)return!0;c=a;return!1})}function Zd(a){a=a.reduce(function(a,c){var b=parseFloat(c.weight);(isNaN(b)||0>b||1<b)&&yc('"weight" field should be a number between (0, 1].');return a+b},0);1!==a&&yc("Sum of all the weights should be equal 1 but got "+a+".")}function $d(a){return fb(a,function(a){return G(a,"weight")})}function yc(a){throw Error("Error in variants setup. "+a);}function nb(a,b,c,d,e){d=((d||0)/1E3).toFixed(2);b={consent:a,publisher_domain_id:na,publisher_id:ma,
decision_time:parseFloat(d),test_case:Ja.id,page_url:b,destination_url:c};zc.setItem("skimCONSENT",a);ka("/consent",b,null,{callback:e})}function ae(a){var b={nocache:Date.now()};Da.get(Ac+"/iab",b,function(b){x=b;p(a)&&a(x)},{withCredentials:!0})}function ob(a){var b={};if(x){var c=va();I(c)&&(b["46"]=c);u(x.partner_consents,function(a,c){I(a.consent)&&(b[c]=a.consent)})}c={nocache:Date.now()};Da.post(Ac+"/iab",c,function(b){x=b;p(a)&&a(x)},{data:JSON.stringify(b),withCredentials:!0})}function be(){var a=
k.country;a&&q(ce,a.toUpperCase())?ae(de):(Bc.setReady(),C.publish("EVENTS__CONSENT_RESOLVED"))}function de(){var a=k.consent,b=k.pageLocation,c=va();I(a)&&null===c?(Ab(a),ob()):I(c)&&c!==a&&nb(c,b,"IAB_CONSENT_SYNC",0);Bc.setReady();C.publish("EVENTS__CONSENT_RESOLVED")}function ee(a,b){var c=y({},fe,b||{}),d=document.createElement("script");d.src=a;d.type="text/javascript";d.async=c.async;d.onload=E(c.onLoad);d.onerror=E(function(){V(new ge(a));c.onError()});document.head.appendChild(d);return d}
function Cc(){if(window._isCypress)return!1;try{return window.top.document,!0}catch(a){return!1}}function pb(a){return Dc()[a]}function he(a,b,c){Ec(a)&&Fc[a]===b?c(pb(a)):ee(b,{onLoad:function(){Ec(a)&&(Fc[a]=b,c(pb(a)))}})}function Ec(a){var b=Dc();return G(b,a)}function Dc(){qa.__SKIM_JS_GLOBAL__||(qa.__SKIM_JS_GLOBAL__={});qa.__SKIM_JS_GLOBAL__.modules||(qa.__SKIM_JS_GLOBAL__.modules={});return qa.__SKIM_JS_GLOBAL__.modules}function ie(a,b,c){var d=document.createElement(a);u(b||{},function(a,
b){var c=b.split(".");wa(d,c,a)});"STYLE"===d.tagName&&(d.type="text/css");"SCRIPT"===d.tagName&&(d.type="text/javascript");Gc(d,[].concat(c||[]));return d}function Gc(a,b){u(b,function(b){if(P(b))Gc(a,b);else{var c="string"===typeof b;"STYLE"===a.tagName&&c&&a.styleSheet?a.styleSheet.cssText+=b:(c&&(b=document.createTextNode(b)),a.appendChild(b))}})}function je(a){var b=A(a.skimlinksOriginalHref||a.href);return ie("a",{href:b,target:"_blank"===a.target?"_blank":"_parent",rel:a.rel})}function Hc(a){var b=
pb(Ja.moduleName);if(b){var c=je(a);c.onclick=function(a){jb(ba.ANCHOR_CLICK_INTERCEPTOR).triggerLeftClickFromMouseEvent(a,oa.SKIMLINKS)};var d=A(a.skimlinksOriginalHref||a.href),e="_blank"===a.target,g=k.pageLocation,n=Date.now(),h=U(function(a){var b=Date.now()-n;Ab(a);if(e)nb(a,g,d,b),ob(),c.click();else{var h=U(function(){c.click()}),r=0,f=function(){r+=1;2===r&&h()};nb(a,g,d,b,f);ob(f);J(h,1E3)}});new b({anchorClone:c,publisherDomain:Q(m.hostname),merchantDomain:ja(d),onResolve:function(){return h(!0)},
onReject:function(){return h(!1)}})}}function ke(){if(le()){var a=Ja.moduleName,b=Ja.getUrl;var c=Sb("skimlinks_locale");var d=Rb(window.location.search).skimlinks_locale;c=c?d:(c=F(x,["country"],k.country))?me[c.toUpperCase()]||"en":"en";c=F(x,["locale"],c);b=b(c);he(a,b,ne)}}function ne(){jb(ba.ANCHOR_CLICK_INTERCEPTOR).registerInterceptor(oe,oa.CONSENT)}function oe(a){if(a.type!==S.LEFT_CLICK)return!1;var b=a.anchor,c=a.nativeEvent;a=a.affiliationType;a=a===w.AFFILIATE||a===w.PRE_AFFILIATED;if(!a)return!1;
c.preventDefault();Hc(b);return!0}function pe(){C.on("skim_js_init",function(){l.__SKIM_JS_GLOBAL__.bundledEntries.GDPRConsent=!0;l.skimlinksAPI.consent={openConsentModal:Hc}});C.on("EVENTS__CONSENT_RESOLVED",ke)}function qe(){return H(Ha(),function(a,b){var c=A(b.href),d=Q(b.hostname),e;(e=!(!W(b,"skimwords-link")&&!W(b,"skimlinks-unlinked"))||!gc(c))||(e=b&&P(Ka)&&0!==Ka.length?xa(b,Ka):!1);if(e)return a;(e=a.urls[c])||(e={count:0,ae:!0===m.aff_domains[d]||(null===m.aff_domains[d]||void 0===m.aff_domains[d])&&
ib&&!Ea(d)?1:0});e.count++;a:{if(-1!==c.indexOf("#slm-")&&(d=c.split("#slm-"),2===d.length&&!isNaN(d[1])&&10*parseInt(d[1],10)===10*d[1])){d=parseInt(d[1],10);break a}d=null}d&&(e.slmcid=d);1===e.ae&&a.count++;e.slmcid&&(d=e.slmcid,q(v.campaign_ids,d)||v.campaign_ids.push(d));if(!Ic&&0===e.ae)return a;a.urls[c]=e;return a},{urls:{},count:0})}function re(){u(se,function(a){var b=l;"skimlinks_context_window"===a&&(b=window);G(b,a)&&(a={page_var:a,value:JSON.stringify(b[a])},a=y({},a,{domain_id:na,publisher_id:ma,
page_url:l.location.href,impression_id:k.uuid,jv:ea}),b={},navigator.sendBeacon?b.useSendBeacon=!1:b.usePixel=!1,ka("/generic_tracking/page_variable_tracking",a,{},b))})}function te(){var a=U(function(){v.linksImpressions.skimlinks=qe();tc("main-tracking");if(Object.keys(v.linksImpressions.skimlinks.urls).length){var a=Eb({dl:v.linksImpressions.skimlinks.urls,hae:v.linksImpressions.skimlinks.count?1:0,typ:"l"});ka("/link",a)}});T.whenNoRequestsPending(a);J(a,2E3)}function ue(){v.awaitedModules.push("main-tracking");
k.skimwordsEnabled&&v.awaitedModules.push("skimwords");k.unlinkedEnabled&&v.awaitedModules.push("unlinked");Jc&&T.whenPostPageLoadBeaconCallCompleted(te);if(navigator.sendBeacon&&1>1E4*Math.random()){var a={domain_id:na,publisher_id:ma,page_url:l.location.href,impression_id:k.uuid,jv:ea},b=bc("/generic_tracking/trackingMethodExperiment",y({trackingMethod:"sendBeacon"},a));cb("/generic_tracking/trackingMethodExperiment",y({trackingMethod:"xhr"},a));b||cb("/generic_tracking/trackingMethodExperiment",
y({trackingMethod:"sendBeaconFailed"},a))}}function ve(){re()}function Kc(a,b){da||1E3<b?p(a)&&(da?qb?a(!0):a(!1):a(!1)):J(Kc,b*=2,a,b)}function Lc(){da||(ra.complete&&sa.complete&&(da=!0),da&&"0"!=ra.width&&"0"==sa.width&&(qb=!0))}function we(a){function b(a){return a.toLowerCase().replace(/^\/\/|^https?:\/\//,"")}var c=Xa(Mc,b);return q(c,b(a))}function xe(){return{skimOptions:ye,runTimeInfo:y({},{aff_domains:m.aff_domains},{consentState:x},{loggedErrors:Ub},k)}}function ze(a,b){var c=!1,d;return function(){if(c)return d;
J(function(){c=!1},b);c=!0;return d=a.apply(this,arguments)}}function Nc(a,b,c,d){void 0===b&&(b=[]);if(a){var e=ze(c,200);u(b,function(b){try{mb(a,b,e,d)}catch(n){}})}}function Ae(){var a=new Be;nc[ba.ANCHOR_CLICK_INTERCEPTOR]=a}function Ce(){l.__SKIM_JS_GLOBAL__||(l.__SKIM_JS_GLOBAL__={});if(!l.__SKIM_JS_GLOBAL__.init){l.skimlinksAPI={};l.__SKIM_JS_GLOBAL__.init=!0;l.__SKIM_JS_GLOBAL__.getDebugInfo=xe;l.__SKIM_JS_GLOBAL__.bundledEntries=De;if(we(m.hostname)||rb&&M.querySelector(rb))k.skimlinksEnabled=
!1,k.skimwordsEnabled=!1,k.unlinkedEnabled=!1;"msie"===k.detect.browser&&8>=k.detect.version&&(k.skimwordsEnabled=!1);try{cc("/robots.txt",void 0,{__skimjs_preflight__please_ignore__:!0})}catch(a){V(new Ee,!0)}Fe.detect(function(a){k.isAdblockUser=a});C.publish("skim_js_init");q(["interactive","complete"],M.readyState)?J(ta,0):(rc(ca.PRE_PAGE_LOAD),document.addEventListener("DOMContentLoaded",ta),document.addEventListener("load",ta));Ae();C.publish("skim_js_start")}}var Vb={log:Aa("log"),info:Aa("info"),
warn:Aa("warn"),error:Aa("error")},Tb=function(){var a=!0;try{var b=[md(),!!(window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest),Ba(document,["querySelector","querySelectorAll"]),Ba(Object,["keys"]),Ba([],["indexOf"]),Ba("",["indexOf"])];a=H(b,function(a,b){return a&&b},!0)}catch(c){a=!1}!1===a&&Vb.info("[Skimlinks] Your browser doesn't support the base features necessary to run our javascript.");return a}();B.prototype=Object.create(Error.prototype,{constructor:{value:Error,enumerable:!1,
writable:!0,configurable:!0}});Pb(B,Error);var $b=B.bind(null,"DocumentBodyNotFound"),Ge=B.bind(null,"PixelDropFailed"),ge=B.bind(null,"ScriptDropFailed"),qd=B.bind(null,"XhrError"),od=B.bind(null,"XhrError4xx"),pd=B.bind(null,"XhrError5xx"),nd=B.bind(null,"XhrErrorZero"),ud=B.bind(null,"SentryLoggerError");B.bind(null,"SendBeaconFailedError");var Ee=B.bind(null,"ResolveSslCertificateError"),ea="14.0.1-stackpath",He="https://s.skimresources.com/js/GDPR",Ie="https://r.skimresources.com/api/",hb={"t.umblr.com":{name:"z"}},
Kb="725X1342",ma=725,na=1342,wd="https://t.skimresources.com/api/v2",Ac="https://api.skimlinks.mgr.consensu.org",dc="go.skimresources.com",Je="https://sl-sentry.skimlinks.com",Oc="f648b8dfc7284fad8af093653eafd6ca",Ke="production",Le=1>1E3*Math.random(),td={sendError:function(a,b){if(!Oc)throw a;var c=b;c=(c=I(c)?c:!1)||Le?a instanceof Ge&&Ob()?!1:!0:!1;if(c){c=Je+"/api/46/store/";var d={sentry_version:"7",sentry_client:"raven-js/3.26.4",
sentry_key:Oc};var e={country:F(za(),["runTimeInfo","country"]),beacon_consent:F(za(),["runTimeInfo","consent"]),iab_consent:F(za(),["runTimeInfo","consentState","skimlinks_consent"]),is_adblock_user:Ob(),is_top_frame:window.top===window};e={event_id:Va(),project:"46",platform:"javascript",logger:"javascript",release:ea,exception:{values:[{type:a.name,value:a.message,stacktrace:{frames:sd(a)}}]},request:{headers:{"User-Agent":navigator.userAgent},url:location.href},extra:y({original_stacktrace:a.stack},
a.__sentryExtraData__,e)};$a(c,d,null,{method:"POST",data:JSON.stringify(e)})}}},Ub=[],Lb=U(function(){return(new Date).getTimezoneOffset()}),Pc=window.skimlinks_context_window||null,l=Pc?window[Pc]:window,M=l.document,zc={getItem:function(a){try{return JSON.parse(localStorage.getItem(a))}catch(b){return null}},setItem:function(a,b){try{localStorage.setItem(a,JSON.stringify(b))}catch(c){}}},sb=f("noskim",!1),Me=f("noskimlinks",!1),Ne=f("noskimwords",!0),Oe=f("nounlinked",
!1),Pe=f("skimwords_standard",false),Qe=f("skimwords_lite",false),Re=f("skimwords_diy",false),Se=f("skimwords_diy_filter",false),Qc=!sb&&!Me,Rc=!sb&&!Ne,Sc=!sb&&!Oe,bb=f("skimlinks_dnt",0,function(a){return a&&"0"!==a&&"false"!==a?1:0}),ac=f("skimlinks_nocookie",!1),tb=f("skimlinks_excluded_classes",[]),hc=f("custom_excluded_selectors",[],
Wb),gb=f("custom_included_selectors",[],Wb),ub=f("skimlinks_exclude",[]),Fa=f("skimlinks_include",[]),ic=f("skimlinks_ignore_hidden_links",false),Ka=f("skimlinks_link_impression_exclude_selector",[]),oc=f("skimlinks_add_nofollow",false),Tc=f("skimlinks_before_click_handler",
false,function(a,b){return I(a)?a:b}),jc=f("skimlinks_first_party_na",!1),Te=f("skimlinks_cookie_sync_optout",!0),Jc=!f("noimpressions",!1),Ic=false,Xb=f("skimlinks_replace_timeout",300,function(a,b){var c=parseFloat(a);return isNaN(c)?b:c}),ib=f("skimlinks_affiliate_unknown_links",true),la=f("skimlinks_target",null),
Ue=f("skimlinks_ajax_rerun",false),N=[],fa=f("skimlinks_revenue_forecast",false),Uc=f("skimlinks_noright",false),Vc=f("skimlinks_url_extraction_rules",!1)||false,Ta=f("skimlinks_extra_redir_params",[]).join("&"),ya=f(["affiliate_tracking","skimlinks_tracking"],!1),La=f("force_location"),X=f(["skimlinks_site","skimlinks_sitename"],!1),vb=f("skimlinks_domain",
"wordpress.redirectingat.com"),Z=f("skimlinks_google",false,function(a,b){return a?I(a)?a?"skimout":"":A(a):b?"skimout":""}),Mc=f("noskim_domains",[]),Ve=f("skimwords_horizontal_distance",80),We=f("skimwords_vertical_distance",80),Xe=false,Oa=f("skimwords_color",null),Pa=f("skimwords_weight",null),
ha=f("skimwords_decoration",null),Qa=f("skimwords_style",null),Ra=f("skimwords_title",null),rb=f("no_skim_selector",""),Wc=f("skimlinks_force_consent",!1),pc=true,ye={SW_STANDARD:Pe,SW_LITE:Qe,SW_DIY:Re,SW_DIY_FILTER:Se,HAS_SKIMLINKS:Qc,HAS_SKIMWORDS:Rc,HAS_UNLINKED:Sc,DO_NOT_TRACK:bb,NO_COOKIE:ac,SL_EXCLUDED_CLASSES:tb,CUSTOM_EXCLUDED_SELECTORS:hc,
CUSTOM_INCLUDED_SELECTORS:gb,SL_EXCLUDED_DOMAINS:ub,SL_INCLUDED_DOMAINS:Fa,SL_IGNORE_HIDDEN_LINKS:ic,SL_IMPRESSION_EXCLUDED_SELECTORS:Ka,SL_ADD_NOFOLLOW:oc,SL_BEFORE_CLICK_HANDLER:Tc,SL_FIRST_PARTY_NA:jc,SL_COOKIE_SYNC_OPTOUT:Te,SL_TRACK_IMPRESSION:Jc,WITH_NA_LINK_IMPRESSIONS:Ic,SL_REPLACE_TIMEOUT:Xb,SL_AFFILIATE_UNKNOWN_LINKS:ib,SL_TARGET:la,AJAX_SUPPORT:Ue,UNLINKED_EXCLUDES:N,SL_FORECAST:fa,NO_RIGHT_CLICK:Uc,USE_MERCHANT_URL_EXTRACTION_RULES:Vc,EXTRA_REDIR_PARAMS:Ta,CUSTOM_TRACKING_VAR:ya,FORCE_LOCATION:La,
SITE_NAME:X,CUSTOM_WAYPOINT_DOMAIN:vb,GOOGLE_TRACKING_ACTION_NAME:Z,NO_SKIM_DOMAINS:Mc,SW_HORIZONTAL_DISTANCE:Ve,SW_VERTICAL_DISTANCE:We,SL_PROFILING:!1,TRACK_COOKIE_SYNCS:Xe,SW_LINK_COLOR:Oa,SW_LINK_WEIGHT:Pa,SW_LINK_DECORATION:ha,SW_LINK_STYLE:Qa,SW_LINK_TITLE:Ra,NO_SKIM_SELECTOR:rb,SL_CONSENT:"ae",FORCE_CONSENT:Wc,M101_TRACKING_ID:null,M101_CUSTOM_DOM_DETECTION:false,AE_CLICK_TRACKING:!1,INCENTIVE_ENABLED:!1,FORCE_PREVENTED_CLICKS_MONETIZATION:pc,
IS_MINIMALISTIC_JS:!1},k=function(){var a=M.referrer||document.referrer||"",b=La||l.location.href;var c="aspsession-id aspsessionid cftoken j-sessionid jsessid jsession_id jsessionid phpsessid phpsession-id phpsessionid seskey sessid session-id session-key session_id sessionid sessionkey uniqueid utm_campaign utm_medium utm_source utm_term".split(" ");for(var d=0;d<c.length;d++){var e=c[d];var g=b.split("?");if(2<=g.length){b=g.shift();g=g.join("?");e=encodeURIComponent(e)+"=";g=g.split(/[&;]/gi);
for(var n=g.length-1;0<=n;n--)Ya(g[n],e)&&g.splice(n,1);b=b+"?"+g.join("&")}}"?"===b[b.length-1]&&(b=b.substr(0,b.length-1));c=b;d=zc.getItem("skimCONSENT");b=navigator.userAgent.toLowerCase();b=/(webkit)[ /]([\w.]+)/.exec(b)||/(opera)(?:.*version)?[ /]([\w.]+)/.exec(b)||/(msie) ([\w.]+)/.exec(b)||0>b.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(b)||[];b={browser:b[1]||"",version:parseFloat(b[2])||0};return{cookieSyncString:"",lastBeaconTimestamp:null,cookie:"",country:"",locale:"",
consent:d,detect:b,isAdblockUser:!1,pageLocation:c,referrer:a,timezone:Lb(),uuid:Va(),skimwordsEnabled:Rc,skimlinksEnabled:Qc,unlinkedEnabled:Sc}}(),m=function(){var a=document.getElementsByTagName("html")?document.getElementsByTagName("html")[0]:null,b=La?ja(La,!1):l.location.hostname;return{aff_domains:{},beacon:[],domain_data:{domains:[]},exclude:ub,exclude_lookup:null,excluded_classes:["noskimlinks","noskim"].concat(tb),has_been_called:!1,hostname:b,html_root:a,include:Fa,include_lookup:null,
links:[],links_tracked:!1,target:null,waypointDomain:vb?"http://"+vb:"https://"+dc}}();var pa={};var Ia={creative:"500005",url_spans:[]};var Xc=function(a,b,c){if(0===b)return c;try{return a()}catch(d){return Xc(a,b-1,c)}};get_real_link=function(a){if(null==a)return null;for(;"A"!==a.nodeName.toUpperCase();)if(a=Xc(function(){return a.parentNode},3,null),null==a)return null;return a};var L,Da={get:function(a,b,c,d){d=y({onError:V},d,{method:"GET"});$a(a,b,E(c),d)},post:function(a,b,c,d){d=y({onError:V},
d,{method:"POST"});$a(a,b,E(c),d)}};"undefined"!==typeof window.Map&&(Y.Cache=Map);var Ye=["noskim","norewrite"],Ze=["noskimlinks","noskim"].concat(["taboola","advert--taboola","trc_rbox","trc_related_container"]),$e="*.criteo.com *.g.doubleclick.net *mjxads.internet.com *overture.com *pgpartner.co.uk *pgpartner.com *pricegrabber.co.uk *pricegrabber.com *youtube.com m.skimresources.com paid.outbrain.com track.celtra.com traffic.outbrain.com trc.taboola.com zergnet.com ad.doubleclick.net".split(" "),
Ad=["itunes.apple.com","itunes.com","phobos.apple.com"],Cd=Y(function(){var a=[].concat(ub,$e);X&&a.push(X);return a}),Db=Y(function(){return Ze.concat(tb).map(function(a){return"."+a})}),Bd=Y(function(){return Ye.map(function(a){return"a[rel~='"+a+"']"})}),af=function(){var a=/[-[\]{}()*+?.,\\^$|#]/g,b=/\s+/g;return function(c){return c.replace(a,"\\$&").replace(b,"\\s+")}}(),w;(function(a){a.AFFILIATE="AFFILIATE";a.PRE_AFFILIATED="PRE_AFFILIATED";a.UNKNOWN="UNKNOWN";a.TRACK="TRACK";a.IGNORE="IGNORE"})(w||
(w={}));var lc="__skimlinks__";var kd=function(a){var b;if(Vc){var c=Q(a.hostname);if(c in hb)return c="[&?]"+hb[c].name+"=(http[^&]+)",c=new RegExp(c),decodeURIComponent(null!=(b=a.href)?b.match(c).pop():void 0)||a.href}return a.href};var Yc;(function(a){a.STARTING="STARTING";a.CANCELLED="CANCELLED";a.PENDING_API="PENDING_API";a.API_ERROR="API_ERROR";a.NO_OFFERS="NO_OFFERS";a.PENDING_MODULE="PENDING_MODULE";a.READY="READY"})(Yc||(Yc={}));var C={topics:{},on:function(a,b,c){P(this.topics[a])||(this.topics[a]=
[]);var d;c&&(d=function(a){Jd(a,c)&&b(a)});this.topics[a].push(d||b)},publish:function(a,b){u(this.topics[a]||[],function(a){p(a)&&a(b)})}},aa=function(){function a(){var a=this;t(this,"ready",void 0);t(this,"pendingCallbacks",void 0);t(this,"subReadyStateList",void 0);t(this,"isReady",function(){return a.dependsOnSubReadyState()?Ld(a.subReadyStateList,function(a){return a.isReady()}):a.ready});t(this,"setReady",function(){a.dependsOnSubReadyState()||a.ready||(a.ready=!0,a.callPendingCallbacks())});
t(this,"waitFor",function(b){a.subReadyStateList=a.subReadyStateList.concat(b);a.isReady()?a.callPendingCallbacks():b.forEach(function(b){b.whenReady(a.whenSubReadyStateIsReady)})});t(this,"whenSubReadyStateIsReady",function(){a.isReady()&&a.callPendingCallbacks()});this.ready=!1;this.pendingCallbacks=[];this.subReadyStateList=[]}var b=a.prototype;b.whenReady=function(a){this.isReady()?a():this.pendingCallbacks.push(a)};b.dependsOnSubReadyState=function(){return 0!==this.subReadyStateList.length};
b.callPendingCallbacks=function(){this.pendingCallbacks.forEach(function(a){setTimeout(a,0)});this.pendingCallbacks=[]};return a}(),ca;(function(a){a.PRE_PAGE_LOAD="PRE_PAGE_LOAD";a.POST_PAGE_LOAD="POST_PAGE_LOAD";a.AUX="AUX"})(ca||(ca={}));var T=new (function(){function a(a,b){var c=this;t(this,"requestBeaconAPI",void 0);t(this,"beaconRequestHandler",void 0);t(this,"requestsHistory",void 0);t(this,"noRequestPendingReadyState",void 0);t(this,"beaconApiResponseReadyState",void 0);t(this,"postPageLoadCallReadyState",
void 0);t(this,"beaconFullyReadyState",void 0);t(this,"whenNoRequestsPending",function(a){c.noRequestPendingReadyState.whenReady(a)});t(this,"whenBeaconApiRequestCompleted",function(a){c.beaconApiResponseReadyState.whenReady(a)});t(this,"whenPostPageLoadBeaconCallCompleted",function(a){c.postPageLoadCallReadyState.whenReady(a)});t(this,"whenBeaconFullyReady",function(a){c.beaconFullyReadyState.whenReady(a)});t(this,"sendBeaconRequest",function(a,b){var d=0===a.length,e={readyState:new aa,requestedDomains:a,
response:null,beaconCallType:b};c.hasFetchedAtLeastOnce()&&d?(c.requestsHistory.push(e),e.readyState.setReady()):c.requestBeaconAPI(a,b,function(b){b=y({requestedDomains:a},b);c.beaconRequestHandler(b);e.response=b;e.readyState.setReady()});c.updateRequestsHistory(e);e.readyState.whenReady(function(){c.resolveReadyStatesOnRequestCompleted(e)});return e});this.requestBeaconAPI=a;this.beaconRequestHandler=b;this.requestsHistory=[];this.noRequestPendingReadyState=new aa;this.noRequestPendingReadyState.setReady();
this.beaconApiResponseReadyState=new aa;this.postPageLoadCallReadyState=new aa;this.beaconFullyReadyState=Md(this.beaconApiResponseReadyState,this.postPageLoadCallReadyState)}var b=a.prototype;b.updateRequestsHistory=function(a){this.requestsHistory.push(a);this.noRequestPendingReadyState.waitFor([a.readyState])};b.resolveReadyStatesOnRequestCompleted=function(a){a.response&&!this.beaconApiResponseReadyState.isReady()&&this.beaconApiResponseReadyState.setReady();a.beaconCallType===ca.POST_PAGE_LOAD&&
this.postPageLoadCallReadyState.setReady()};b.hasFetchedAtLeastOnce=function(){return 0!==this.requestsHistory.length};return a}())(function(a,b,c){a=JSON.stringify({pubcode:Kb,page:l.location.href,domains:a});a={headers:{"Content-type":"application/x-www-form-urlencoded"},data:ia({data:a}),withCredentials:!0};var d=Ua();"production"!==Ke&&(d._=b);Da.post(""+Ie,d,c,a)},function(a){var b={};a.country&&(b.country=a.country.toUpperCase());a.guid&&""===k.cookie&&(b.cookie=a.guid);I(a.consent)&&(b.consent=
a.consent);a.csp&&(b.cookieSyncString=a.csp);a.ts&&(b.lastBeaconTimestamp=a.ts);y(k,b);Kd(a.requestedDomains,a.merchant_domains)}),ba;(ba||(ba={})).ANCHOR_CLICK_INTERCEPTOR="ANCHOR_CLICK_INTERCEPTOR";var nc={},S;(function(a){a.LEFT_CLICK="LEFT_CLICK";a.MIDDLE_CLICK="MIDDLE_CLICK";a.OTHER_CLICK="OTHER_CLICK"})(S||(S={}));var oa;(function(a){a[a.CONSENT=0]="CONSENT";a[a.INCENTIVE=1]="INCENTIVE";a[a.SKIMLINKS=2]="SKIMLINKS"})(oa||(oa={}));var Zc={}.hasOwnProperty;var wb=0;var xb=null;var yb=0;var Ma=
!1;var Na={};var bf=function(a){Na[a]=Na[a]||0;Na[a]++;return a+"_"+Na[a]};var cf=function(a){var b;var c=b=null;if(-1!==a.indexOf(".")){a=a.split(".");var d=a[0];c=a[1]}else-1!==a.indexOf("[class=")?(a=a.split("[class="),d=a[0],c=a[1].split("]"),c=c[0]):-1!==a.indexOf("[class^=")?(a=a.split("[class^="),d=a[0],c=a[1].split("]"),c=c[0]):-1!==a.indexOf("[id*=")?(a=a.split("[id*="),d=a[0],b=a[1].split("]"),b=b[0]):d=a;return{tag:d,id:b,"class":c}};var ua=function(a,b){var c;var d=b.split(",");var e=
0;for(c=d.length;e<c;e++){b=d[e];b=A(b);b=cf(b);var g=!0;var n=(n="string"===typeof a.className?a.className:"")||("function"===typeof a.getAttribute?a.getAttribute("class"):void 0)||"";var h=("function"===typeof a.getAttribute?a.getAttribute("id"):void 0)||"";!b.tag||a.nodeName&&a.nodeName.toLowerCase()===b.tag||(g=!1);b["class"]&&(!n||n!==b["class"]&&0!==n.indexOf(b["class"]))&&(g=!1);b.id&&(!h||h!==b.id&&-1===h.indexOf(b.id))&&(g=!1);if(g)return!0}return!1};var $c=function(a,b){return ua(a,b)?[a]:
mc(a.querySelectorAll(b))};var df=function(a,b){return 0<a.querySelectorAll(b).length};var zb=function(a,b){return 0===b.length||ua(a,b.join(","))?!0:a.parentNode?zb(a.parentNode,b):!1};var ad=function d(b,c){return 0===c.length?!1:ua(b,c.join(","))?!0:b.parentNode?d(b.parentNode,c):!1};var ef=function(b){var c=b.offsetWidth;b=b.offsetHeight;return 468===c&&60===b||234===c&&60===b||728===c&&90===b||300===c&&250===b||250===c&&250===b||336===c&&280===b||160===c&&600===b||120===c&&600===b?!0:!1};var ff=
function(){var b=[];b.push("div.widget-content");b.push("div.googleAdText");b.push("div[id=ad]");b.push("div[id=banner]");b.push("div[id=advertisement]");b.push("div[id=adv_container]");b.push("div.ad");b.push("div.banner");b.push("div.advertisement");b.push("div.ad_container");b.push("span.IL_AD");b.push("div[id=fave-ext-container]");b.push("span.skimlinks-unlinked");-1!==l.location.href.indexOf(".google.")?(b.push("td.gac_c"),b.push("table[id=mbEnd]"),b.push("div[id=mbEnd]"),b.push("span[id=taw]"),
b.push("td.std"),b.push("div.std"),b.push("table.gssb_e"),b.push("div.c"),b.push("div[id=tads]")):-1!==l.location.href.indexOf(".yahoo.")?(b.push("ul.spns,ul.reducepx-spnslist"),b.push("ul[class*=reducepx-spnslist]"),b.push("ul[id=east]")):-1!==l.location.href.indexOf(".aol.")?(b.push("div.sllLink"),b.push("div.n")):-1!==l.location.href.indexOf(".bing.")&&(b.push("div.sb_adsW"),b.push("div[id=sidebar]"),b.push("div.sb_adsWv2"),b.push("div.sb_adsNv2"),b.push("div[class*=sb_ads]"));return b};var gf=
function(b){var c;var d={};var e=0;for(c=b.length;e<c;e++){var g=b[e];d[g]=!0}return d};var hf=function(){wb=0;C.publish("dom_changed")};var jf=function(b,c,d,e){var g,n,h;if((g=b.className||("function"===typeof b.getAttribute?b.getAttribute("class"):void 0)||"")&&("skimlinks-unlinked"===g||"skimwords-link"===g))return!1;if(0===d.length&&0===c.length)return z.traverse_node(b,!1,"","",e);if(0!==d.length){if(!ad(b,d)){g=z.get_exclude_selector(d);d=z.get_exclude_selector([]);var r=g.selector;var f=g.needed;
var k=d.selector;if(0===c.length||zb(b,c))return z.traverse_node(b,f,k,r,e);g=[];var l=0;for(h=c.length;l<h;l++){d=c[l];var m=$c(b,d);m.length?g.push(function(){var b;var c=[];var d=0;for(b=m.length;d<b;d++)n=m[d],c.push(z.traverse_node(n,f,k,r,e));return c}()):g.push(void 0)}return g}}else if(0!==c.length){if(zb(b,c))return z.traverse_node(b,!1,"","",e);h=[];g=0;for(l=c.length;g<l;g++)d=c[g],m=$c(b,d),m.length?h.push(function(){var b;var c=[];var d=0;for(b=m.length;d<b;d++)n=m[d],c.push(z.traverse_node(n,
!1,"","",e));return c}()):h.push(void 0);return h}};E(function(b){b=b.relatedNode||!1;if(!b||pa.send_in_progress||f("stop_skimwords_ajax"))return!1;xb&&clearTimeout(xb);wb++;1===wb&&z.reset();jf(b,pa.settings.includes||[],pa.settings.excludes||[],pa.settings.read_onlys||[]);if(z.get_non_colliding_nodes()&&1<=yb)return xb=J(function(){hf()},1E3)});var z=function(){var b={};return{traverse:function(c,d,e,g){c=c||[];d=d||[];e=e||[];return b&&b.length&&!g?b:this.traverse_dom(c,d,e)},traverse_dom:function(c,
d,e){var g,n;if(Ma)return b;Ma=!0;var h=this.get_exclude_selector(d);var r=this.get_exclude_selector([]);d=h.selector;h=h.needed;r=r.selector;0===c.length&&c.push("body");c=c.concat(e);for(var f=0,k=c.length;f<k;f++){var l=c[f];l=qc(l);l=document.querySelectorAll(l);var m=g=0;for(n=l.length;g<n;m=++g)m=l[m],this.traverse_node(m,h,r,d,e)}return b},traverse_node:function(c,d,e,g,n){var h=[];var f=0;for(h.push({node:c,tagName:"",readOnly:!1,parent_id:null});f<h.length;)!(c=h[f].node)||ef(c)||W(c,"noskimwords")||
W(c,"noskim")||d&&""!==e&&ua(c,e)||(h[f].readOnly=!1,c.nodeName&&"#text"!==c.nodeName?(h[f].tagName=c.nodeName,null!==h[f].parent_id&&(h[f].readOnly=h[h[f].parent_id].readOnly),h[f].readOnly||(d&&ua(c,g)?h[f].readOnly=!0:q(n,c.nodeName.toLowerCase())&&(h[f].readOnly=!0)),q(n,c.nodeName.toLowerCase())&&(h[f].readOnly=!0)):null!==h[f].parent_id&&(h[f].tagName=h[h[f].parent_id].tagName,h[f].readOnly=h[h[f].parent_id].readOnly),"msie"===k.detect.browser&&9>k.detect.version&&h[f].readOnly||(c.hasChildNodes()?
h=this.add_child_nodes(h[f],f,h):this._add(c,!1,h[f].tagName,h[f].readOnly))),f++;return b},is_traversed:function(){return Ma},is_good_tag:function(b){return gf("p body div span ul ol li table tbody td tr th tfoot col colgroup em strong big small blockquote cite b dl dfn dd dt ins form legend noframes pre noscript center font i article section main".split(" "))[b.nodeName.toLowerCase()]?!0:!1},is_html:function(b){return(b=A(b))&&"<"===b[0]},get_non_colliding_nodes:function(){var c;var d=b;var e={};
yb=0;for(c in d)Zc.call(d,c)&&(e[c]=d[c],yb++);return e},get_as_hash_node_dict:function(){var c;var d={};for(c in b){var e=b[c];G(b,c)&&(d[c]=e)}return d},get_as_pair_array:function(){var c;var d=[];for(c in b)Zc.call(b,c)&&d.push([c,b[c]]);return d},get_exclude_selector:function(b,d){var c,g,f;var h=[];if(!d){d=document.getElementsByTagName("body");if(!d.length)return{needed:!1,selector:""};d=d[0]}b=b.concat(ff());var k=c=0;for(g=b.length;c<g;k=++c)b[k]=qc(b[k]);c=!1;g="";var l=0;for(f=b.length;l<
f;l++)k=b[l],df(d,k)&&h.push(k);h.length&&(c=!0,g=h.join(",").replace("class=","class^="));return{needed:c,selector:g}},length:function(){return Object.keys(b).length},reset:function(){b=[];return Ma=!1},add_child_nodes:function(b,d,e){var c,f;var h=b.node.childNodes;var k=0;for(f=h.length;k<f;k++)(c=h[k])&&c.nodeName&&!this._add(c,!1,b.tagName,b.readOnly)&&this.is_good_tag(c)&&e.push({node:c,tagName:b.tagName,readOnly:b.readOnly,parent_id:d});return e},add_node:function(b,d){return this._add(b,d)},
_add:function(c,d,e,g){var f=null;"#text"===c.nodeName&&(f=A(c.nodeValue));d=d||!1;if("msie"===k.detect.browser&&9>k.detect.version&&g)return!1;if("msie"!==k.detect.browser||9<=k.detect.version)try{c.meta={ElementTag:e,ReadOnly:g}}catch(h){}if(f&&!this.is_html(f)&&3<=f.length){if(d&&"-1"===d)return!1;d=this._skim_id_hash(f,d);if(!d)return!1;b[d]=c}return f?!0:!1},_skim_id_hash:function(b){if(!b)return"";var c=A(b.replace(/\s+/g," ")).length;b=b.replace(/[:\s]*/g,"");c=c+":"+b.substring(0,20);return c=
bf(c)}}}();var Wd=function(b,c,d){if(fa)return!1;var e=(b.data?b.data:b.childNodes[0].data).replace(c.repl_regex,c.replacement);var g=document.createElement("span");c=document.createDocumentFragment();g.innerHTML=e;if("msie"===k.detect.browser&&9>k.detect.version){e=b.previousSibling;var f=/^\s/;e&&e.nodeValue&&e.nodeValue.length&&f.test(e.nodeValue[e.nodeValue.length-1])&&(e.nodeValue+=" ");(e=b.nextSibling)&&e.nodeValue&&e.nodeValue.length&&f.test(e.nodeValue[0])&&(e.nodeValue=" "+e.nodeValue)}for(;g.firstChild;)"#text"===
g.firstChild.nodeName?(e=c.appendChild(g.firstChild),z.add_node(e)):(e=c.appendChild(g.firstChild),null===e||d||Fb(e,!0));if(d=b.parentNode)return d.replaceChild(c,b)};var v={campaign_ids:[],loading_started:(new Date).getTime(),linksImpressions:{skimlinks:{count:0,urls:{}},skimwords:{count:0,urls:{}},unlinked:{count:0,urls:{}}},awaitedModules:[]},hd=[".noskim",".noskimwords",".noskimw"];var Xd=function(b){mb(b,"click",uc);Uc||mb(b,"contextmenu",uc);return Fb(b,!1)};var kf=function(b,c,d,e){var g=
af(b);c=lb(c);g="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/:\\?])?("+g+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/:\\?])*(?:[\\s]+|$)";b=Za(lb(b));c='$1$2<a href="'+c+'" class="'+e+'"  data-skimwords-word="'+b+'"  data-skim-creative="'+d+'" title="">$3$4</a>$5$6';d=g.replace(/\?:/g,"");return{search_regex:new RegExp(g,"i"),repl_regex:new RegExp(d,"i"),repl_text:c}};var ed=function(b,c){var d,e,g;if(!b||ad(b,["span.skimlinks-unlinked"]))return[[],[]];var f=b.data;var h=[];var l=[];for(e=/$|\b(?:https?:\/\/)?(?:[-_a-zA-Z]+\.)*(?:[-_a-zA-Z]{2,}\.[-_\w]{2,5}\b)[^[\]\s]*\b|$/gi;d=
e.exec(f);){var m=d[0];if("link.phrase"!==m){var t=d.index;if(0<A(m).length&&-1===m.indexOf("/.")&&-1===m.indexOf("...")){var q=m;0!==m.indexOf("http")&&0!==m.indexOf("//")&&(q="msie"===k.detect.browser&&6>=k.detect.version?"http://"+m:"//"+m);d=ja(q);var u=id({OriginalPhrase:""+m,Url:q,Title:"",ActionType:2,GroupId:0,Unlinked:!0});(g=kf(""+m,q,Ia.creative,"skimlinks-unlinked"))&&l.push({start:t,text:""+lb(m),domain:d,repl_regex:g.repl_regex,replacement:g.repl_text,regex:g.search_regex,phrase:u,link:q});
h.push(d)}else break}}if(l.length){var p=c;q="skimlinks-unlinked";var w;m=document.createDocumentFragment();var v=0;d=[];t=b.nodeValue;e=[];f=b.parentNode;q||(q="skimwords-potential");p||(p="-1");if(f){u=0;for(w=l.length;u<w;u++){var x=l[u];var y=document.createElement("span");y.className=q;g=document.createTextNode(t.substring(v,x.start));m.appendChild(g);y.innerHTML=x.text;m.appendChild(y);v={};v.node=y;v.match=x;D(v,"occurrence",x.target_occurrence);d.push(v);v=x.start+x.text.length;e.push(g);
z.add_node(g,p)}l=document.createTextNode(t.substring(v));e.push(l);m.appendChild(l);z.add_node(l,p);f.replaceChild(m,b)}p=[d,e];l=p[0];p=p[1];m=0;for(e=l.length;m<e;m++)f=l[m],Ia.url_spans.push(f)}p||(p=[]);return[h,p]};var fd=function(b){var c;if(m.exclude.length){var d=m.exclude;var e=0;for(c=d.length;e<c;e++){var g=d[e];if(g===b)return!1}}if(m.include.length){d=m.include;e=0;for(c=d.length;e<c;e++)if(g=d[e],g===b)return!0;return!1}return!0};var ce="AT BE BG CY CZ DE DK EE ES FI FR GB GR HR HU IE IT LT LU LV MT NL PL PT RO SE SI SK".split(" ");
B.bind(null,"InvalidVariantConfig");var Ja=function(b){$d(b)?(Zd(b),b=Yd(b)):b=b[Math.floor(b.length*Math.random())];return b}([{id:1,moduleName:"ConsentA",getUrl:function(b,c){return function(d){d=q(c,d)?d:"en";return He+"/Consent_"+b+"_"+d+".js"}}("A",["bg","de","el","en","es","fr","it","pl","pt","sk"])}]),me={AT:"de",BE:"fr",BG:"bg",CY:"el",CZ:"cs",DE:"de",DK:"da",EE:"et",ES:"es",FI:"fi",FR:"fr",GB:"en",GR:"el",HR:"hr",HU:"hu",IE:"en",IT:"it",LT:"lt",LU:"fr",LV:"lv",MT:"en",NL:"en",PL:"pl",PT:"pt",RO:"ro",SE:"sv",
SI:"sl",SK:"sk"},cd=[{label:"lotame",url:"https://sync.crwdcntrl.net/map/c=7505/tp=SKIM/?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dlotame%26skim_mapping%3Dtrue%26provider_id%3D%24%7Bprofile_id%7D",resyncAfter:[2,"days"],priority:1,iabVendorId:95,active:!0},{label:"blue_kai",url:"https://stags.bluekai.com/site/27381?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dblue_kai%26skim_mapping%3Dtrue%26provider_id%3D%24_BK_UUID",resyncAfter:[1,"days"],priority:2,iabVendorId:null,active:!0},
{label:"dfp",url:"https://cm.g.doubleclick.net/pixel?google_nid=skimlinks_ddp&google_cm",resyncAfter:[1,"days"],priority:2,iabVendorId:null,active:!0},{label:"mediamath",url:"https://pixel.mathtag.com/sync/img?redir=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Dmediamath%26skim_mapping%3Dtrue%26provider_id%3D%5BMM_UUID%5D%26provider_dc%3D%5BMT_DC%5D",resyncAfter:[1,"days"],priority:2,iabVendorId:79,active:!0},{label:"app_nexus",url:"https://secure.adnxs.com/getuid?https%3A%2F%2Fx.skimresources.com%2F%3Fprovider_id%3D%24UID%26provider%3Dapp_nexus%26skim_mapping%3Dtrue",
resyncAfter:[1,"days"],priority:2,iabVendorId:32,active:!0},{label:"eyeota",url:"https://ps.eyeota.net/match?gdpr=${SKIM__GDPR_APPLICABLE}&gdpr_consent=${SKIM__CONSENT_STRING}&bid=dn9h51u&r=https%3A%2F%2Fx.skimresources.com%2F%3Fprovider%3Deyeota%26provider_id%3D%7BUUID_dn9h51u%7D%26skim_mapping%3Dtrue",resyncAfter:[1,"days"],priority:2,iabVendorId:120,active:!0},{label:"exelate",url:"https://x.skimresources.com/?provider=exelate",resyncAfter:[1,"days"],priority:1,iabVendorId:373,active:!0},{label:"exelate_dbm",
url:"https://cm.g.doubleclick.net/pixel?google_nid=exelate&google_cm&google_sc",resyncAfter:[2,"days"],priority:2,iabVendorId:null,active:!0,includedCountries:["GB","DE","IT","FR","ES"]},{label:"exelate_tradedesk",url:"https://match.adsrvr.org/track/cmf/generic?ttd_pid=exelate&ttd_tpi=1",resyncAfter:[2,"days"],priority:2,iabVendorId:21,active:!0,includedCountries:["GB","DE","IT"]},{label:"avocet",url:"https://ads.avocet.io/getuid?url=https%3A%2F%2Fx.skimresources.com%2F%3Fskim_mapping%3Dtrue%26provider%3Davocet%26provider_id%3D%7B%7BUUID%7D%7D",
resyncAfter:[1,"days"],priority:3,iabVendorId:63,active:!0},{label:"tapad",url:"https://x.skimresources.com/?provider=tapad",resyncAfter:[3,"days"],priority:3,iabVendorId:89,active:!0},{label:"trade_desk",url:"https://match.adsrvr.org/track/cmf/generic?ttd_pid=qakudad&ttd_tpi=1",resyncAfter:[3,"days"],priority:3,iabVendorId:21,active:!0},{label:"zeotap_dbm",url:"https://x.skimresources.com/?provider=zeotap_dbm",resyncAfter:[5,"days"],priority:2,iabVendorId:null,active:!0},{label:"zeotap_us_latam",
url:"https://x.skimresources.com/?provider=zeotap_us_latam",resyncAfter:[5,"days"],priority:2,iabVendorId:null,active:!0,includedCountries:"US MX BR PE CL AR CO".split(" ")}],Bc=new aa,x={},fe={async:!0,onError:function(){},onLoad:function(){}},qa=Cc()?window.top:window,Fc={},lf="AT BE BG CY DE ES FR GB GR IE IT LU MT NL PL PT SK".split(" "),le=U(function(){var b=Cc()?window.top:window;if(p(b.__cmp)||"msie"===k.detect.browser&&8>=k.detect.version)return!1;if(Wc||Sb("skimlinks_force_consent"))return!0;
var c=va();b=F(x,["country"],k.country);c=I(c);b=!!b&&q(lf,b.toUpperCase());return!c&&b}),se=["skimlinks_included_ids","skimlinks_byrel","skimlinks_exrel","skimlinks_included_classes"],qb=!1,da=!1,ra=null,sa=null,Fe={detect:function(b){a:{try{var c=navigator.userAgent.toLowerCase();if(-1===c.indexOf("firefox")&&-1===c.indexOf("chrome")){da=!0;qb=!1;break a}}catch(d){}c=""+11*Math.random();ra=new Image;ra.onload=Lc;ra.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"1").replace(/\*/,c);sa=
new Image;sa.onload=Lc;sa.src="//p.skimresources.com/px.gif?ch=*&rn=*".replace(/\*/,"2").replace(/\*/,c)}Kc(b,250)}},bd=Qb([!!Tc&&"mouseup","click"]),mf=["auxclick","contextmenu","touchstart"],Be=function(){function b(){var b=this;t(this,"interceptors",void 0);t(this,"onClick",function(c,d){var e=Gb(c);e&&(e.skimlinksOriginalHref&&e.skimlinksRestoreSwappedLink(),e=b.createAnchorClickEvent(c,e),b.dispatchAnchorClick(e,d))});t(this,"createAnchorClickEvent",function(c,d){var e=b.getInternalClickType(c),
g=Dd(d);return{type:e,anchor:d,affiliationType:g,clientClickId:Va(),nativeEvent:c}});t(this,"registerInterceptor",function(c,d){if(!p(c))throw Error("InterceptorHandler should be a function");if(K(d))throw Error("Missing priority for click interceptor");b.interceptors.push({handler:c,priority:d});b.interceptors.sort(function(b,c){return b.priority-c.priority})});t(this,"triggerLeftClickFromMouseEvent",function(c,d){var e=b.findInterceptorsWithPriority(d);if(K(d))b.onClick(c);else if(e.length)b.onClick(c,
e)});this.interceptors=[];this.initGlobalClickHandler()}var c=b.prototype;c.initGlobalClickHandler=function(){Nc(M,bd,this.onClick,!0);Nc(M,mf,this.onClick,!0)};c.getInternalClickType=function(b){return q(bd,b.type)&&0===b.button?S.LEFT_CLICK:"auxclick"!==b.type&&"click"!==b.type||1!==b.button?S.OTHER_CLICK:S.MIDDLE_CLICK};c.dispatchAnchorClick=function(b,c){(c||this.interceptors).some(function(c){c=c.handler;return c(b)})};c.findInterceptorsWithPriority=function(b){return Wa(this.interceptors,function(c){return c.priority===
b})};return b}(),ta=E(function(){rc(ca.POST_PAGE_LOAD);document.removeEventListener("DOMContentLoaded",ta);document.removeEventListener("load",ta)}),De={skimlinks:!1,skimwords:!1,unlinked:!1,audience:!1,GDPRConsent:!1,incentivePopup:!1};Tb&&E(function(){C.on("skim_js_init",Rd);C.on("skim_js_init",Ud);T.whenBeaconApiRequestCompleted(be);pe();C.on("skim_js_init",ue);C.on("skim_js_start",ve);Ce()})()})();
