# Generated by Django 3.0.5 on 2020-04-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_file',
            field=models.FileField(blank=True, upload_to='blog_pdf'),
        ),
    ]
