# Generated by Django 3.0.5 on 2020-04-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200425_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='enotes',
            name='blog_file',
            field=models.FileField(blank=True, upload_to='blog_pdf'),
        ),
    ]
