# Generated by Django 3.0.5 on 2020-04-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_enotes_blog_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enotes',
            old_name='blog_file',
            new_name='fileMy',
        ),
    ]
