# Generated by Django 3.0.5 on 2020-04-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200425_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enotes',
            name='academic_year',
            field=models.CharField(choices=[('FY', 'I'), ('SY', 'II'), ('TY', 'III'), ('BE', 'IV')], default='I', max_length=100),
        ),
    ]
