# Generated by Django 3.0.6 on 2020-05-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_pracs'),
    ]

    operations = [
        migrations.AddField(
            model_name='enotes',
            name='sub_new',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pracs',
            name='sub_new',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quespaper',
            name='sub_new',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
