# Generated by Django 2.1.1 on 2020-06-26 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200507_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enotes',
            name='sub',
            field=models.CharField(choices=[('NO SUBJECT', 'NO SUBJECT'), ('DSF', 'Data Structures And Files'), ('DSGT', 'Data Structures and Graph Theory'), ('AM2', 'Applied Mathematcs'), ('AM1', 'Applied Mechanics'), ('EI', 'Engineering Informatics'), ('DBMS', 'DBMS'), ('SYSTEM ENGG', 'SYSTEM ENGG'), ('MATHS', 'MATHS'), ('PSYCHO', 'PSYCHO'), ('MATERIAL ENGG', 'MATERIAL ENGG'), ('PYTHON', 'PYTHON'), ('CPP', 'CPP'), ('EEE', 'EEE'), ('None', 'none')], default='NO SUBJECT', help_text='if sub not in the list, write sub in sub_new', max_length=100),
        ),
        migrations.AlterField(
            model_name='enotes',
            name='sub_new',
            field=models.CharField(blank=True, help_text='write full name of subject like not DEM but Digital Electronics and Microprocessors', max_length=100),
        ),
        migrations.AlterField(
            model_name='pracs',
            name='sub',
            field=models.CharField(choices=[('NO SUBJECT', 'NO SUBJECT'), ('DSF', 'Data Structures And Files'), ('DSGT', 'Data Structures and Graph Theory'), ('AM2', 'Applied Mathematcs'), ('AM1', 'Applied Mechanics'), ('EI', 'Engineering Informatics'), ('DBMS', 'DBMS'), ('SYSTEM ENGG', 'SYSTEM ENGG'), ('MATHS', 'MATHS'), ('PSYCHO', 'PSYCHO'), ('MATERIAL ENGG', 'MATERIAL ENGG'), ('PYTHON', 'PYTHON'), ('CPP', 'CPP'), ('EEE', 'EEE'), ('None', 'none')], default='NO SUBJECT', help_text='if sub not in the list, write sub in sub_new', max_length=100),
        ),
        migrations.AlterField(
            model_name='pracs',
            name='sub_new',
            field=models.CharField(blank=True, help_text='write full name of subject like not DEM but Digital Electronics and Microprocessors', max_length=100),
        ),
        migrations.AlterField(
            model_name='quespaper',
            name='exam_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='YYYY-DD-MM'),
        ),
        migrations.AlterField(
            model_name='quespaper',
            name='sub',
            field=models.CharField(choices=[('NO SUBJECT', 'NO SUBJECT'), ('DSF', 'Data Structures And Files'), ('DSGT', 'Data Structures and Graph Theory'), ('AM2', 'Applied Mathematcs'), ('AM1', 'Applied Mechanics'), ('EI', 'Engineering Informatics'), ('DBMS', 'DBMS'), ('SYSTEM ENGG', 'SYSTEM ENGG'), ('MATHS', 'MATHS'), ('PSYCHO', 'PSYCHO'), ('MATERIAL ENGG', 'MATERIAL ENGG'), ('PYTHON', 'PYTHON'), ('CPP', 'CPP'), ('EEE', 'EEE'), ('None', 'none')], default='NO SUBJECT', help_text='if sub not in the list, write sub in sub_new', max_length=100),
        ),
        migrations.AlterField(
            model_name='quespaper',
            name='sub_new',
            field=models.CharField(blank=True, help_text='write full name of subject like not DEM but Digital Electronics and Microprocessors', max_length=100),
        ),
    ]
