# Generated by Django 2.1.1 on 2020-06-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200626_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enotes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='pracs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='quespaper',
            name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog_file',
        ),
        migrations.AddField(
            model_name='post',
            name='img1',
            field=models.ImageField(default='default.jpg', upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.ImageField(default='default.jpg', upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='img3',
            field=models.ImageField(default='default.jpg', upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='img4',
            field=models.ImageField(default='default.jpg', upload_to='post_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='rent_day',
            field=models.PositiveIntegerField(blank=True, default=50),
        ),
        migrations.AddField(
            model_name='post',
            name='rent_hour',
            field=models.PositiveIntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='post',
            name='rent_month',
            field=models.PositiveIntegerField(blank=True, default=200),
        ),
        migrations.AddField(
            model_name='post',
            name='rent_week',
            field=models.PositiveIntegerField(blank=True, default=100),
        ),
        migrations.AddField(
            model_name='post',
            name='sell_price',
            field=models.PositiveIntegerField(blank=True, default=300),
        ),
        migrations.DeleteModel(
            name='Enotes',
        ),
        migrations.DeleteModel(
            name='Pracs',
        ),
        migrations.DeleteModel(
            name='QuesPaper',
        ),
    ]
