# Generated by Django 2.2.3 on 2020-07-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200627_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopCat',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='MobileCat',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
                ('brand', models.CharField(choices=[('Samsung', 'Samsung'), ('Redmi', 'Redmi'), ('Oppo', 'Oppo'), ('Vivo', 'Vivo'), ('iPhone', 'iPhone'), ('MicroMax', 'MicroMax'), ('Other', 'Other')], default='Other', max_length=100)),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('laptopcat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.LaptopCat')),
                ('brand', models.CharField(choices=[('Lenovo', 'Lenovo'), ('Dell', 'Dell'), ('HP', 'HP'), ('Viao', 'Viao'), ('Mac', 'Mac'), ('Other', 'Other')], default='Other', max_length=100)),
                ('gaming', models.BooleanField(default=False)),
            ],
            bases=('blog.laptopcat',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('laptopcat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.LaptopCat')),
                ('brand', models.CharField(choices=[('Lenovo', 'Lenovo'), ('Dell', 'Dell'), ('HP', 'HP'), ('Vaio', 'Vaio'), ('Mac', 'Mac'), ('Other', 'Other')], default='Other', max_length=100)),
                ('ram', models.PositiveIntegerField(blank=True, default=6, help_text='GB')),
                ('internal_memory', models.PositiveIntegerField(blank=True, default=32, help_text='GB')),
                ('processor', models.PositiveIntegerField(blank=True, default=5, help_text='core i5')),
                ('internal_graphic_card', models.CharField(choices=[('Lenovo', 'Lenovo'), ('Dell', 'Dell'), ('HP', 'HP'), ('Vaio', 'Vaio'), ('Mac', 'Mac'), ('Other', 'Other')], default='Other', max_length=100)),
                ('iGB', models.PositiveIntegerField(blank=True, default=4, help_text='GB')),
                ('external_graphic_card', models.CharField(choices=[('Lenovo', 'Lenovo'), ('Dell', 'Dell'), ('HP', 'HP'), ('Vaio', 'Vaio'), ('Mac', 'Mac'), ('Other', 'Other')], default='Other', max_length=100)),
                ('eGB', models.PositiveIntegerField(blank=True, default=4, help_text='GB')),
            ],
            bases=('blog.laptopcat',),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('mobilecat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.MobileCat')),
                ('ram', models.PositiveIntegerField(blank=True, default=6, help_text='GB')),
                ('internal_memory', models.PositiveIntegerField(blank=True, default=32, help_text='GB')),
                ('front_camera', models.PositiveIntegerField(blank=True, default=32, help_text='MP')),
                ('rear_camera', models.PositiveIntegerField(blank=True, default=32, help_text='MP')),
            ],
            bases=('blog.mobilecat',),
        ),
        migrations.CreateModel(
            name='MobileCharger',
            fields=[
                ('mobilecat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.MobileCat')),
                ('port_type', models.CharField(choices=[('type-C', 'type-C'), ('type-A', 'type-A'), ('other', 'other')], default='other', max_length=100)),
                ('original', models.BooleanField(default=False)),
                ('cable_length', models.PositiveIntegerField(blank=True, help_text='metre', null=True)),
                ('voltage', models.PositiveIntegerField(blank=True, help_text='Volts', null=True)),
                ('ampere', models.PositiveIntegerField(blank=True, help_text='Ampere', null=True)),
            ],
            bases=('blog.mobilecat',),
        ),
        migrations.CreateModel(
            name='MobileCover',
            fields=[
                ('mobilecat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.MobileCat')),
            ],
            bases=('blog.mobilecat',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('laptopcat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.LaptopCat')),
                ('brand', models.CharField(choices=[('Lenovo', 'Lenovo'), ('Dell', 'Dell'), ('HP', 'HP'), ('Viao', 'Viao'), ('Mac', 'Mac'), ('Other', 'Other')], default='Other', max_length=100)),
                ('gaming', models.BooleanField(default=False)),
            ],
            bases=('blog.laptopcat',),
        ),
    ]
