# Generated by Django 2.2.3 on 2020-07-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_keyboard_laptop_laptopcat_mobile_mobilecat_mobilecharger_mobilecover_mouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='with_helmet',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scooty',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
