# Generated by Django 2.2.3 on 2020-07-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200718_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='with_helmet',
            field=models.BooleanField(default=False),
        ),
    ]
