# Generated by Django 2.2.3 on 2020-07-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200718_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twowheeler',
            name='year',
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='bought year', null=True),
        ),
    ]
