# Generated by Django 2.2.5 on 2020-09-19 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20200718_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCat',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Engg',
            fields=[
                ('bookcat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BookCat')),
                ('branch', models.CharField(choices=[('Computer', 'Computer'), ('Mechanical', 'Mechanical'), ('ENTC', 'ENTC'), ('Chemical', 'Chemical'), ('Civil', 'Civil'), ('ETX', 'ETX')], default='Computer', max_length=100)),
                ('subject', models.CharField(default='Computer Networks', max_length=100)),
            ],
            bases=('blog.bookcat',),
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('bookcat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BookCat')),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Comedy', 'Comedy'), ('Classic', 'Classic'), ('Biography', 'Biography'), ('Action', 'Action'), ('Nonfiction', 'Nonfiction'), ('Mystery', 'Mystery'), ('Fantasy', 'Fantasy'), ('Drama', 'Drama')], default='Classic', max_length=100)),
                ('novel_author', models.CharField(default='anonymous', max_length=100)),
            ],
            bases=('blog.bookcat',),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('bookcat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BookCat')),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('StateBoard', 'StateBoard'), ('other', 'other')], default='CBSE', max_length=100)),
                ('std', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='12', max_length=100)),
                ('subject', models.CharField(default='Math', max_length=100)),
            ],
            bases=('blog.bookcat',),
        ),
        migrations.DeleteModel(
            name='Bicycle',
        ),
    ]
