# Generated by Django 2.2.5 on 2020-10-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200919_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
            ],
            bases=('blog.post',),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img1',
            field=models.ImageField(default='default.jpg', upload_to='post_images', verbose_name='image 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img2',
            field=models.ImageField(default='default.jpg', upload_to='post_images', verbose_name='image 2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img3',
            field=models.ImageField(default='default.jpg', upload_to='post_images', verbose_name='image 3'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img4',
            field=models.ImageField(default='default.jpg', upload_to='post_images', verbose_name='image 4'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rent_day',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rent price per day'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rent_hour',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rent price per hour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rent_month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rent price per month'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rent_week',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rent price per week'),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='bought year', null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='twowheeler',
            name='cc',
            field=models.PositiveIntegerField(blank=True, help_text='CC', null=True, verbose_name='CC'),
        ),
        migrations.AlterField(
            model_name='twowheeler',
            name='km',
            field=models.PositiveIntegerField(blank=True, help_text='KM driven', null=True, verbose_name='KM'),
        ),
    ]
