# Generated by Django 2.2.5 on 2020-10-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20201029_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='HouseHold',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
            ],
            bases=('blog.post',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Post')),
            ],
            bases=('blog.post',),
        ),
    ]
